### ISSUE TITLE
were is NN & MC ?

### ISSUE THREAD

**Issue by tissatussa** [FireFather/fire-HCE#1]
your previous version 8 had NNUE (raptor.bin) and MCTS mode .. however 8.11 seems to lack these options .. did you change the core ?  Your current README does not mention NNUE and MCTS either.

**Comment by tissatussa** [comment]
ohhh .. now i see : https://github.com/FireFather/fire-NN offers it ..

**Comment by FireFather** [comment]
I'm now maintaining 2 different repositories...
one for Fire (this one) https://github.com/FireFather/fire
and one for Fire NN https://github.com/FireFather/fire-NN
